# Generated by Django 5.1.4 on 2025-01-15 13:39

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('developTool', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Idea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_date', models.DateTimeField(auto_created=True, auto_now=True, verbose_name='수정일')),
                ('created_date', models.DateTimeField(auto_created=True, auto_now_add=True, verbose_name='작성일')),
                ('title', models.CharField(max_length=100, verbose_name='제목')),
                ('image', models.ImageField(blank=True, upload_to='idea/%Y%m%d')),
                ('content', models.TextField(verbose_name='내용')),
                ('interest', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)], verbose_name='관심도')),
                ('starred', models.BooleanField(default=False)),
                ('devtool', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='developTool.devtool', verbose_name='개발 도구')),
            ],
        ),
    ]
