# Generated by Django 5.1.4 on 2025-01-15 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DevTool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=30, verbose_name='이름')),
                ('kind', models.CharField(default='', max_length=40, verbose_name='종류')),
                ('content', models.TextField(default='', verbose_name='내용')),
            ],
        ),
    ]
