# Generated by Django 5.1.4 on 2025-01-09 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_review_rate_review_written_at_alter_review_actor_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='rate',
            field=models.FloatField(default=5.0),
        ),
        migrations.AlterField(
            model_name='review',
            name='running_time',
            field=models.TextField(default=0),
        ),
    ]
