# Generated by Django 5.1.4 on 2025-01-10 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0003_alter_review_rate_alter_review_running_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='poster',
            field=models.ImageField(null=True, upload_to='reviews'),
        ),
    ]
