# Generated by Django 5.1.4 on 2025-01-10 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0004_review_poster'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='poster',
            field=models.ImageField(blank=True, null=True, upload_to='reviews/'),
        ),
    ]
