# Generated by Django 5.1.4 on 2025-01-10 11:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0005_alter_review_poster'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='poster',
        ),
    ]
